name: Build latest master and deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, self-hosted ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.12.0
        with:
          java-version: 21
          java-distribution: liberica
          checkout-persist-credentials: true
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build with Maven
        run: mvn spring-boot:build-image

      - name: Push Images to Docker Registry
        run: docker push -a bjoggis/linode4j
  manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: pull-arm64
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          retry_wait_seconds: 60
          max_attempts: 8
          command: docker pull bjoggis/linode4j:v0.0.0-aarch_64
      - name: create-manifest
        run: |
          docker manifest create bjoggis/linode4j:v0.0.0 --amend bjoggis/linode4j:v0.0.0-x86_64 --amend bjoggis/linode4j:v0.0.0-aarch_64
          docker manifest push bjoggis/linode4j:v0.0.0
          docker manifest create bjoggis/linode4j:latest --amend bjoggis/linode4j:v0.0.0-x86_64 --amend bjoggis/linode4j:v0.0.0-aarch_64
          docker manifest push bjoggis/linode4j:latest
